name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Install dependencies if using CocoaPods (uncomment if applicable)
    # - name: Install CocoaPods dependencies
    #   run: pod install
    #   working-directory: .

    # Resolve Swift Package Manager dependencies
    - name: Resolve Swift Package Manager dependencies
      run: |
        xcodebuild -resolvePackageDependencies

    # Clean and Build the project
    - name: Clean and Build
      run: |
        xcodebuild clean build \
        -scheme RickAndMortyExplorer \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'

    # Run tests (if available)
    - name: Run Tests
      run: |
        xcodebuild test \
        -scheme RickAndMortyExplorer \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
